homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat 
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

hacs:
  token: !secret github_key
  theme: true
  python_script: true
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

mqtt:
  discovery_prefix: homeassistant
  discovery: true
  broker: localhost
  port: 1884
  
# Discover some devices automatically
discovery:

binary_sensor:
  - platform: ping
    host: google.com
    count: 2
    scan_interval: 30
    name: Google
  - platform: ping
    host: !secret gateway
    count: 2
    scan_interval: 30
    name: Gateway
  - platform: ping
    host: !secret publicip
    count: 2
    scan_interval: 30
    name: PublicIP
  - platform: ping
    host: 192.168.100.1
    count: 2
    scan_interval: 30
    name: Modem
  - platform: wyzesense
    device: "/dev/hidraw1"
# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

sensor: !include_dir_merge_list config/sensors
group: !include config/groups.yaml
automation: !include config/automations/automations.yaml
script: !include scripts.yaml

panel_iframe:
  esphome:
    title: esphome
    url: !secret esphome_url
    icon: mdi:banana

media_player:
  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_key
    ssl: true
    port: 8096

  - platform: xboxone
    device: !secret xbox_id
    name: Living Room Xbox One
    ip_address: !secret xbox_ip

  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_key
   
#pihole ad count
pi_hole:
  host: !secret pihole_host

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key
    mode: freedaily

camera:
  - platform: generic
    still_image_url: !secret camera_1_still
    verify_ssl: false
    username: !secret camera_user
    password: !secret camera_pass
    stream_source: !secret camera_1_stream
    framerate: 5
    name: Kitchen

camera 2:
  - platform: generic
    still_image_url: !secret camera_2_still
    verify_ssl: false
    username: !secret camera_user
    password: !secret camera_pass
    stream_source: !secret camera_2_stream
    framerate: 5
    name: Garage

transmission:
  host: !secret transmission_host
  
google_assistant:
  project_id: !secret google_assistant_project
  api_key: !secret google_assistant_key
  exposed_domains:
    - switch
    - binary_sensor
    - light
    - camera
    - script
    - input_boolean

roku:
  - host: !secret livingroom_tv

input_boolean:
  front_motion:
    name: Front Door Motion Announcements
    icon: mdi:motion-sensor
  
  motion_email:
    name: Email Image on Motion
    icon: mdi:email

  warframe:
    name: warframe
    icon: mdi:xbox

  ordis:
    name: Ordis
    icon: mdi:codepen

  guest_mode:
    name: Guest Mode
    icon: mdi:human-male-female

  party_mode:
    name: Party Mode
    icon: mdi:firework

  default_mode:
    name: Default Mode
    icon: mdi:home
  
  night_mode:
    name: Night Mode
    icon: mdi:sleep
  
  weekend_mode:
    name: Weekend Mode
    icon: mdi:sofa #find better

climate:
  - platform: radiotherm
    host:
      - !secret thermostat_ip

mobile_app:
