homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat 
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

mqtt:
  discovery_prefix: homeassistant
  discovery: true
  broker: localhost
  port: 1884
  
# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: openweathermap
    api_key: !secret openweathermap_key
    monitored_conditions:
      - weather
      - temperature
  # cable modem
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(2) > td:nth-of-type(5)"
    name: downstream1
    unit_of_measurement: 'db'
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(3) > td:nth-of-type(5)"
    name: downstream2
    unit_of_measurement: 'db'
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(4) > td:nth-of-type(5)"
    name: downstream3
    unit_of_measurement: 'db'
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(5) > td:nth-of-type(5)"
    name: downstream4
    unit_of_measurement: 'db'
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(6) > td:nth-of-type(5)"
    name: downstream5
    unit_of_measurement: 'db' 
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(7) > td:nth-of-type(5)"
    name: downstream6
    unit_of_measurement: 'db' 
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(8) > td:nth-of-type(5)"
    name: downstream7
    unit_of_measurement: 'db' 
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(9) > td:nth-of-type(5)"
    name: downstream8
    unit_of_measurement: 'db' 
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(10) > td:nth-of-type(5)"
    name: downstream9
    unit_of_measurement: 'db' 
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(11) > td:nth-of-type(5)"
    name: downstream10
    unit_of_measurement: 'db' 
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(12) > td:nth-of-type(5)"
    name: downstream11
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(13) > td:nth-of-type(5)"
    name: downstream12
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(14) > td:nth-of-type(5)"
    name: downstream13
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(15) > td:nth-of-type(5)"
    name: downstream14
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(16) > td:nth-of-type(5)"
    name: downstream15
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(17) > td:nth-of-type(5)"
    name: downstream16
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(18) > td:nth-of-type(5)"
    name: downstream17
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(19) > td:nth-of-type(5)"
    name: downstream18
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(20) > td:nth-of-type(5)"
    name: downstream19
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(21) > td:nth-of-type(5)"
    name: downstream20
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(22) > td:nth-of-type(5)"
    name: downstream21
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(23) > td:nth-of-type(5)"
    name: downstream22
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(24) > td:nth-of-type(5)"
    name: downstream23
    unit_of_measurement: 'db'  
  - platform: scrape
    resource: http://192.168.100.1/cgi-bin/status_cgi
    select: "tr:nth-of-type(25) > td:nth-of-type(5)"
    name: downstream24
    unit_of_measurement: 'db'  

  #pihole ad count
  - platform: pi_hole
    host: !secret pihole_host
  #ping 
  - platform: template
    sensors:
      publicip:
        value_template: '{% if is_state("binary_sensor.publicip", "on") %} {{ states.binary_sensor.publicip.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
        unit_of_measurement: 'ms'
      google:
        value_template: '{% if is_state("binary_sensor.google", "on") %} {{ states.binary_sensor.google.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
        unit_of_measurement: 'ms'
      gateway:
        value_template: '{% if is_state("binary_sensor.gateway", "on") %} {{ states.binary_sensor.gateway.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
        unit_of_measurement: 'ms'
      modem:
        value_template: '{% if is_state("binary_sensor.modem", "on") %} {{ states.binary_sensor.modem.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
        unit_of_measurement: 'ms'

binary_sensor:
  - platform: ping
    host: google.com
    count: 2
    scan_interval: 30
    name: Google
  - platform: ping
    host: !secret gateway
    count: 2
    scan_interval: 30
    name: Gateway
  - platform: ping
    host: !secret publicip
    count: 2
    scan_interval: 30
    name: PublicIP
  - platform: ping
    host: 192.168.100.1
    count: 2
    scan_interval: 30
    name: Modem

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_pass
    verify_ssl: false

media_player:
  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_key
    ssl: true
    port: 8096

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key
    mode: freedaily

camera:
  - platform: generic
    still_image_url: !secret camera_1_still
    verify_ssl: false
    username: !secret camera_user
    password: !secret camera_pass
    stream_source: !secret camera_1_stream
    framerate: 5
    name: LivingRoom

camera 2:
  - platform: generic
    still_image_url: !secret camera_2_still
    verify_ssl: false
    username: !secret camera_user
    password: !secret camera_pass
    stream_source: !secret camera_2_stream
    framerate: 5
    name: Front Porch

transmission:
  host: !secret transmission_host
  monitored_conditions: 
    - download_speed
    - upload_speed
    - started_torrents

google_assistant:
  project_id: !secret google_assistant_project
  api_key: !secret google_assistant_key
  exposed_domains:
    - switch
    - light
    - camera
    - script

#cast:
#  media_player:
#    - host: !secret living_room_speaker

googlehome:
  devices:
    - host: !secret living_room_speaker
      track_alarms: true

roku:
  - host: !secret livingroom_tv
