- id: '1559938294913'
  alias: DownloadComplete
  trigger:
  - platform: webhook
    webhook_id: downloadcomplete
  condition: []
  action:
  - data_template:
      message: New movie on Emby. {{ trigger.json.movie.title }} is now available.
    entity_id: media_player.googlehome1053
    service: tts.google_say
